"""update book table

Revision ID: 568b759ea1a1
Revises: 2198c99ff529
Create Date: 2026-01-02 14:06:06.589609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568b759ea1a1'
down_revision: Union[str, Sequence[str], None] = '2198c99ff529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(length=255), nullable=False))
    op.add_column('books', sa.Column('year_published', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_column('books', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('books', 'summary')
    op.drop_column('books', 'year_published')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
